---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: username/app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 상점
  labels:
    app: 상점
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 상점
  template:
    metadata:
      labels:
        app: 상점
    spec:
      containers:
        - name: 상점
          image: username/상점:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 결제
  labels:
    app: 결제
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 결제
  template:
    metadata:
      labels:
        app: 결제
    spec:
      containers:
        - name: 결제
          image: username/결제:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryMen
  labels:
    app: deliveryMen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryMen
  template:
    metadata:
      labels:
        app: deliveryMen
    spec:
      containers:
        - name: deliveryMen
          image: username/deliveryMen:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: app


---


apiVersion: v1
kind: Service
metadata:
  name: 상점
  labels:
    app: 상점
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 상점


---


apiVersion: v1
kind: Service
metadata:
  name: 결제
  labels:
    app: 결제
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 결제


---


apiVersion: v1
kind: Service
metadata:
  name: deliveryMen
  labels:
    app: deliveryMen
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deliveryMen

